version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    container_name: ${CONTAINER_NAME}
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
